server:
  port: 7070
spring:
  application:
    name: seat-service
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_auth_micro?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: caron
    password: 12130519