server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: seat-service # 路由标示，必须唯一
          uri: lb://seatService # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/seat/** # 路径断言，判断路径是否是以/user开头，如果是则符合
#          局部路由 优先级 第二低
#          filters:
#            - AddRequestHeader=Truth,Itcast is freaking awesome!
        - id: book-service
          uri: lb://bookService
          predicates:
            - Path=/book/**
#      全局路由过滤器 优先级最低
#      路由过滤器和defaultFilter的order由Spring指定，默认是按照声明顺序从1递增。
#      default-filters:
#        - AddRequestHeader=Truth,Itcast is freaking awesome!  #给所有请求头加上信息