server:
  port: 6522
spring:
  application:
    name: bookService
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_auth_micro?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true
    username: caron
    password: 12130519
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}


web:
  service-path: http://localhost:9090/
  upload-path: C:/Users/Caron/Desktop/Library-master-microservices



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true     # 下划线转驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 实体类映射日志
  global-config:
    banner: true
    db-config:
      logic-delete-field: delete
      logic-delete-value: 1
      logic-not-delete-value: 0